Repository WebUI-Project-Based-10-nr/BackEnd, pull requests merged in 2024-10, with the labels that each got.

#69 Set up SonarCloud backend integration
  .github/workflows/main.yaml
  sonar-project.properties
Labels: Backend, feature, sprint 1

#72 Add unit tests for error middleware, coverage 100%
  package-lock.json
  package.json
  src/test/unit/middlewares/error-middleware.spec.js
Labels: Backend, sprint 2, test

#74 [GoogleAuth] Connect Google login to the project
  src/controllers/auth.js
  src/routes/auth.js
  src/services/auth.js
  src/test/unit/middlewares/auth.spec.js
  src/validation/schemas/googleAuth.js
Labels: Backend, feature, sprint 1

#75 Add unit test with coverage 100% for Validation Middleware
  src/test/unit/middlewares/validation.spec.js
Labels: Backend, sprint 2, test

#78 Add tests for middleware language
  src/test/unit/middlewares/app-language.spec.js
Labels: Backend, sprint 2, test

#79 Add Email Confirmation to Google Auth
  src/controllers/auth.js
  src/routes/auth.js
  src/services/auth.js
  src/test/unit/middlewares/auth.spec.js
  src/validation/schemas/emailConfirmation.js
Labels: Backend, feature, sprint 1

#81 Add null from default for NativeLanguage on user.js
  src/models/user.js
Labels: bug, Backend, sprint 2

#84 Implement endpoints used in Subjects step
  src/consts/models.js
  src/controllers/category.js
  src/controllers/subject.js
  src/models/category.js
  src/models/subject.js
  src/routes/category.js
  src/routes/index.js
  src/routes/subject.js
  src/services/category.js
  src/services/subject.js
  src/test/integration/controllers/category.spec.js
  src/test/integration/controllers/subject.spec.js
Labels: Backend
