Repository WebUI-Project-Based-10-nr/BackEnd, pull requests merged in 2024-11, with the labels that each got.

#90 fixed searching question by name
  src/utils/getMatchOptions.js
Labels: bug, Backend

#91 (SP: 2) Create "Subject" model
  src/swagger-schemas/subject-schema.yaml
Labels: Backend

#93 Add validation for subject module
  src/models/offer.js
Labels: Backend, feature, sprint 5

#92 Add get subjects endpoint
  src/controllers/subject.js
  src/routes/subject.js
  src/services/subject.js
  src/test/integration/controllers/subject.spec.js
  src/test/unit/services/subject.spec.js
Labels: Backend, feature

#98 Add getCategoryById endpoint
  src/controllers/category.js
  src/routes/category.js
  src/services/category.js
  src/test/integration/controllers/category.spec.js
  src/test/unit/services/category.spec.js
Labels: Backend, feature

#94 (SP: 2) Implement "GetSubjectById" endpoint
  src/controllers/subject.js
  src/routes/subject.js
  src/services/subject.js
  src/test/integration/controllers/subject.spec.js
Labels: Backend

#97 Feature/27/lesson model
  src/models/lesson.js
  src/swagger-schemas/lesson-schema.yaml
Labels: Backend, feature

#102 Add "Quiz" model
  src/models/quiz.js
  src/swagger-schemas/quiz-schema.yaml
  src/test/integration/models/quiz.spec.js
Labels: Backend, feature
